### ISSUE TITLE
Just installed and getting a lot of Notices

### ISSUE THREAD

**Issue by afilina** [sebastianbergmann/phpdcd#55] opened 2015-03-23 00:53 UTC
I installed the phar version 1.0.2 on my PHP 5.5.14 and ran:
$phpdcd foldername

Getting a lot of Notice: Undefined index: line in phar:///usr/local/bin/phpdcd/src/Analyser.php on line 274

**Comment by sebastianbergmann** [comment] 2015-03-23 05:43
As I wrote on Twitter, this is not really supported. PhpStorm's detection of unused code is much better.

**Comment by DanielRuf** [comment] 2015-06-30 08:17
@sebastianbergmann That phpdcd scans itself and throws many notices?

This is the same command like you write in the readme `php phpdcd.phar`

**Comment by hackel** [comment] 2015-07-22 17:26
I'm also seeing this:
```
PHP Notice:  Undefined index:  in vendor/sebastian/phpdcd/src/Analyser.php on line 274
PHP Stack trace:
PHP   1. {main}() vendor/sebastian/phpdcd/phpdcd:0
PHP   2. Symfony\Component\Console\Application->run() vendor/sebastian/phpdcd/phpdcd:64
PHP   3. SebastianBergmann\PHPDCD\CLI\Application->doRun() vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRun() vendor/sebastian/phpdcd/src/CLI/Application.php:136
PHP   5. Symfony\Component\Console\Application->doRunCommand() vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   6. Symfony\Component\Console\Command\Command->run() vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   7. SebastianBergmann\PHPDCD\CLI\Command->execute() vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
PHP   8. SebastianBergmann\PHPDCD\Detector->detectDeadCode() vendor/sebastian/phpdcd/src/CLI/Command.php:137
PHP   9. SebastianBergmann\PHPDCD\Analyser->analyseFile() vendor/sebastian/phpdcd/src/Detector.php:69
PHP  10. SebastianBergmann\PHPDCD\Analyser->analyseSourceCode() vendor/sebastian/phpdcd/src/Analyser.php:159
PHP Notice:  Undefined index: line in vendor/sebastian/phpdcd/src/Analyser.php on line 274
PHP Stack trace:
PHP   1. {main}() vendor/sebastian/phpdcd/phpdcd:0
PHP   2. Symfony\Component\Console\Application->run() vendor/sebastian/phpdcd/phpdcd:64
PHP   3. SebastianBergmann\PHPDCD\CLI\Application->doRun() vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRun() vendor/sebastian/phpdcd/src/CLI/Application.php:136
PHP   5. Symfony\Component\Console\Application->doRunCommand() vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   6. Symfony\Component\Console\Command\Command->run() vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   7. SebastianBergmann\PHPDCD\CLI\Command->execute() vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
PHP   8. SebastianBergmann\PHPDCD\Detector->detectDeadCode() vendor/sebastian/phpdcd/src/CLI/Command.php:137
PHP   9. SebastianBergmann\PHPDCD\Analyser->analyseFile() vendor/sebastian/phpdcd/src/Detector.php:69
PHP  10. SebastianBergmann\PHPDCD\Analyser->analyseSourceCode() vendor/sebastian/phpdcd/src/Analyser.php:159
PHP Notice:  Undefined index: file in vendor/sebastian/phpdcd/src/Log/Text.php on line 72
PHP Stack trace:
PHP   1. {main}() vendor/sebastian/phpdcd/phpdcd:0
PHP   2. Symfony\Component\Console\Application->run() vendor/sebastian/phpdcd/phpdcd:64
PHP   3. SebastianBergmann\PHPDCD\CLI\Application->doRun() vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRun() vendor/sebastian/phpdcd/src/CLI/Application.php:136
PHP   5. Symfony\Component\Console\Application->doRunCommand() vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   6. Symfony\Component\Console\Command\Command->run() vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   7. SebastianBergmann\PHPDCD\CLI\Command->execute() vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
PHP   8. SebastianBergmann\PHPDCD\Log\Text->printResult() vendor/sebastian/phpdcd/src/CLI/Command.php:141
PHP Notice:  Undefined index: line in vendor/sebastian/phpdcd/src/Log/Text.php on line 73
PHP Stack trace:
PHP   1. {main}() vendor/sebastian/phpdcd/phpdcd:0
PHP   2. Symfony\Component\Console\Application->run() vendor/sebastian/phpdcd/phpdcd:64
PHP   3. SebastianBergmann\PHPDCD\CLI\Application->doRun() vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRun() vendor/sebastian/phpdcd/src/CLI/Application.php:136
PHP   5. Symfony\Component\Console\Application->doRunCommand() vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   6. Symfony\Component\Console\Command\Command->run() vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   7. SebastianBergmann\PHPDCD\CLI\Command->execute() vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
PHP   8. SebastianBergmann\PHPDCD\Log\Text->printResult() vendor/sebastian/phpdcd/src/CLI/Command.php:141
```

@sebastianbergmann What is the supported usage?  I want to integrate this in my CI (Jenkins), so PhpStorm is quite useless.

**Comment by hackel** [comment] 2015-07-22 17:28
Whoops, this is actually a dupe of #45.  Wow, that's an old bug!  Any chance of getting #52 merged?

**Comment by sebastianbergmann** [comment] 2015-07-22 18:17
As I said in https://github.com/sebastianbergmann/phpdcd/issues/55#issuecomment-84817607, I don't really maintain this project anymore. It never really worked and cannot be made to work in a useful way (see https://github.com/sebastianbergmann/phpdcd#limitations).

**Comment by DanielRuf** [comment] 2015-07-22 19:49
> As I said in #55 (comment), I don't really maintain this project anymore. It never really worked and cannot be made to work in a useful way (see https://github.com/sebastianbergmann/phpdcd#limitations).

Well, many users will see phpdcd, use it and run into the same issue(s).

I did not know that you are not maintaining this anymore as there is no information about this in the readme.

**Comment by Eternal-Infinity** [comment] 2015-07-24 07:55
I was also surprised to read that this project isn't maintained anymore.
As someone who doesn't use Twitter, this was some hard news for me :(

It may be that PHPStrom has a way better detection for unused code, but what about people (like me) who don't use PHPStorm?

I think this project had (and still has) lot potential and I really home that someone will keep maintaining this project.
It would be awesome, maybe I even try to dig myself deeper into the code to see if I could contribute something here.

**Comment by DanielRuf** [comment] 2015-07-24 08:18
> I was also surprised to read that this project isn't maintained anymore.
> As someone who doesn't use Twitter, this was some hard news for me :(
> 
> It may be that PHPStrom has a way better detection for unused code, but what about people (like me) who don't use PHPStorm?
> 
> I think this project had (and still has) lot potential and I really hope that someone will keep maintaining this project.
> It would be awesome, maybe I even try to dig myself deeper into the code to see if I could contribute something here.

:+1:

**Comment by hackel** [comment] 2015-07-30 20:33
@sebastianbergmann Sorry, I didn't understand that you meant the entire project wasn't supported!  Perhaps you could just add a note to the README so people know not to bug you and/or expect it to work in its current state.  @theseer I discovered this project on http://phpqatools.org/ so perhaps it should be removed from there as well.

**Comment by DanielRuf** [comment] 2015-07-30 20:40
> @sebastianbergmann Sorry, I didn't understand that you meant the entire project wasn't supported! Perhaps you could just add a note to the README so people know not to bug you and/or expect it to work in its current state. @theseer I discovered this project on http://phpqatools.org/ so perhaps it should be removed from there as well.

:+1:

**Comment by theseer** [comment] 2015-07-30 21:12
@hackel Iagree with you but @sebastianbergmann would have to update the content as I only control the dns for the domain.

**Comment by sebastianbergmann** [comment] 2015-07-31 03:35
http://phpqatools.org/ has been updated.

**Comment by sebastianbergmann** [comment] 2015-10-12 14:31
I lost interest in this project a long time ago, mostly due to the [limitations](https://github.com/sebastianbergmann/phpdcd#limitations) of its implementation. Today I [added](https://github.com/sebastianbergmann/phpdcd/commit/69885271da311d3e849706306ae038f775d1ee99) a note that this project is no longer maintained to its documentation and closed all open tickets. Feel free to continue to work on this in a fork.

**Closed by sebastianbergmann** 2015-10-12 14:31 UTC
